export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT = "LOGOUT";

export const ADD_SUPPLIERS_REQUEST = "ADD_SUPPLIERS_REQUEST";
export const ADD_SUPPLIERS_FAIL = "ADD_SUPPLIERS_FAIL";
export const ADD_SUPPLIERS_SUCCESS = "ADD_SUPPLIERS_SUCCESS";

export const DELETE_SUPPLIERS_REQUEST = "DELETE_SUPPLIERS_REQUEST";
export const DELETE_SUPPLIERS_FAIL = "DELETE_SUPPLIERS_FAIL";
export const DELETE_SUPPLIERS_SUCCESS = "DELETE_SUPPLIERS_SUCCESS";

export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_REQUEST = "GET_SUPPLIERS_REQUEST";
export const GET_SUPPLIERS_FAIL = "GET_SUPPLIERS_FAIL";

export const UPDATE_SUPPLIER_REQUEST = "UPDATE_SUPPLIER_REQUEST";
export const UPDATE_SUPPLIERS_SUCCESS = "UPDATE_SUPPLIERS_SUCCESS";
export const UPDATE_SUPPLIERS_FAIL = "UPDATE_SUPPLIERS_FAIL";

export const ADD_BRAND_REQUEST = "ADD_BRAND_REQUEST";
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS";
export const ADD_BRAND_FAIL = "ADD_BRAND_FAIL";

export const GET_BRANDS_REQUEST = "GET_BRANDS_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAIL = "GET_BRAND_FAIL";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAIL = "DELETE_BRAND_FAIL";

export const UPDATE_BRANDS_REQUEST = "UPDATE_BRANDS_REQUEST";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_FAIL";

export const ADD_SERVICE_CATEGORY_REQUEST = "ADD_SERVICE_CATEGORY_REQUEST";
export const ADD_SERVICE_CATEGORY_SUCCESS = "ADD_SERVICE_CATEGORY_SUCCESS";
export const ADD_SERVICE_CATEGORY_FAIL = "ADD_SERVICE_CATEGORY_FAIL";

export const GET_SERVICE_CATEGORIES_REQUEST = "GET_SERVICE_CATEGORIES_REQUEST";
export const GET_SERVICE_CATEGORIES_SUCCESS = "GET_SERVICE_CATEGORIES_SUCCESS";
export const GET_SERVICE_CATEGORIES_FAIL = "GET_SERVICE_CATEGORIES_FAIL_";

export const DELETE_SERVICE_CATEGORY_REQUEST = "DELETE_SERVICE_CATEGORY_REQUEST";
export const DELETE_SERVICE_CATEGORY_SUCCESS = "DELETE_SERVICE_CATEGORY_SUCCESS";
export const DELETE_SERVICE_CATEGORY_FAIL = "DELETE_SERVICE_CATEGORY_FAIL";

export const UPDATE_SERVICE_CATEGORY_REQUEST = "UPDATE_SERVICE_CATEGORY_REQUEST";
export const UPDATE_SERVICE_CATEGORY_SUCCESS = "UPDATE_SERVICE_CATEGORY_SUCCESS";
export const UPDATE_SERVICE_CATEGORY_FAIL = "UPDATE_SERVICE_CATEGORY_FAIL";


export const ADD_SERVICE_PAYMENT_REQUEST = "ADD_SERVICE_PAYMENT_REQUEST";
export const ADD_SERVICE_PAYMENT_SUCCESS = "ADD_SERVICE_PAYMENT_SUCCESS";
export const ADD_SERVICE_PAYMENT_FAIL = "ADD_SERVICE_PAYMENT_FAIL";

export const GET_SERVICE_PAYMENT_REQUEST = "GET_SERVICE_PAYMENT_REQUEST";
export const GET_SERVICE_PAYMENT_SUCCESS = "GET_SERVICE_PAYMENT_SUCCESS";
export const GET_SERVICE_PAYMENT_FAIL = "GET_SERVICE_PAYMENT_FAIL";

export const DELETE_SERVICE_PAYMENT_REQUEST = "DELETE_SERVICE_PAYMENT_REQUEST";
export const DELETE_SERVICE_PAYMENT_SUCCESS = "DELETE_SERVICE_PAYMENT_SUCCESS";
export const DELETE_SERVICE_PAYMENT_FAIL = "DELETE_SERVICE_PAYMENT_FAIL";

export const UPDATE_SERVICE_PAYMENT_REQUEST = "UPDATE_SERVICE_PAYMENT_REQUEST";
export const UPDATE_SERVICE_PAYMENT_SUCCESS = "UPDATE_SERVICE_PAYMENT_SUCCESS";
export const UPDATE_SERVICE_PAYMENT_FAIL = "UPDATE_SERVICE_PAYMENT_FAIL";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const GET_PRODUCT_BY_BARCODE_REQUEST = "GET_PRODUCT_BY_BARCODE_REQUEST";
export const GET_PRODUCT_BY_BARCODE_SUCCESS = "GET_PRODUCT_BY_BARCODE_SUCCESS";
export const GET_PRODUCT_BY_BARCODE_FAIL = "GET_PRODUCT_BY_BARCODE_FAIL";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const ADD_SALES_REQUEST = "ADD_SALES_REQUEST";
export const ADD_SALES_SUCCESS = "ADD_SALES_SUCCESS";
export const ADD_SALES_FAIL = "ADD_SALES_FAIL";

export const UPDATE_SALES_REQUEST = "UPDATE_SALES_REQUEST";
export const UPDATE_SALES_SUCCESS = "UPDATE_SALES_SUCCESS";
export const UPDATE_SALES_FAIL = "UPDATE_SALES_FAIL";

export const DELETE_SALES_REQUEST = "DELETE_SALES_REQUEST";
export const DELETE_SALES_SUCCESS = "DELETE_SALES_SUCCESS";
export const DELETE_SALES_FAIL = "DELETE_SALES_FAIL";

export const ADD_SALES_DATA_REQUEST = "ADD_SALES_DATA_REQUEST";
export const ADD_SALES_DATASUCCESS = "ADD_SALES_DATA_SUCCESS";
export const ADD_SALES_DATA_FAIL = "ADD_SALES_DATA_FAIL";

export const GET_TOTAL_SALES_REQUEST = "GET_TOTAL_SALES_REQUEST";
export const GET_TOTAL_SALES_SUCCESS = "GET_TOTAL_SALES_SUCCESS";
export const GET_TOTAL_SALES_FAIL = "GET_TOTAL_SALES_FAIL";

export const ADD_STAFF_REQUEST = "ADD_STAFF_REQUEST";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAIL = "ADD_STAFF_FAIL";

export const GET_STAFF_REQUEST = "GET_STAFF_REQUEST";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const GET_STAFF_FAIL = "GET_STAFF_FAIL";

export const DELETE_STAFF_REQUEST = "DELETE_STAFF_REQUEST";
export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS";
export const DELETE_STAFF_FAIL = "DELETE_STAFF_FAIL";

export const SUSPEND_STAFF_REQUEST = "SUSPEND_STAFF_REQUEST";
export const SUSPEND_STAFF_SUCCESS = "SUSPEND_STAFF_SUCCESS";
export const SUSPEND_STAFF_FAIL = "SUSPEND_STAFF_FAIL";

export const UPDATE_STAFF_REQUEST = "UPDATE_STAFF_REQUEST";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";
export const UPDATE_STAFF_FAIL = "UPDATE_STAFF_FAIL";

export const GET_STORE_REQUEST = "GET_STORE_REQUEST";
export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const GET_STORE_FAIL = "GET_STORE_FAIL";

export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST";
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS";
export const ADD_STORE_FAIL = "ADD_STORE_FAIL";

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";

export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_PURCHASE_REQUEST = "GET_PURCHASE_REQUEST";
export const GET_PURCHASE_SUCCESS = "GET_PURCHASE_SUCCESS";
export const GET_PURCHASE_FAIL = "GET_PURCHASE_FAIL";

export const ADD_PURCHASE_REQUEST = "ADD_PURCHASE_REQUEST";
export const ADD_PURCHASE_SUCCESS = "ADD_PURCHASE_SUCCESS";
export const ADD_PURCHASE_FAIL = "ADD_PURCHASE_FAIL";

export const UPDATE_PURCHASE_REQUEST = "UPDATE_PURCHASE_REQUEST";
export const UPDATE_PURCHASE_SUCCESS = "UPDATE_PURCHASE_SUCCESS";
export const UPDATE_PURCHASE_FAIL = "UPDATE_PURCHASE_FAIL";

export const DELETE_PURCHASE_REQUEST = "DELETE_PURCHASE_REQUEST";
export const DELETE_PURCHASE_SUCCESS = "DELETE_PURCHASE_SUCCESS";
export const DELETE_PURCHASE_FAIL = "DELETE_PURCHASE_FAIL";

export const ADD_PAYMENT_TYPE_REQUEST = "ADD_PAYMENT_TYPE_REQUEST";
export const ADD_PAYMENT_TYPE_FAIL = "ADD_PAYMENT_TYPE_FAIL";
export const ADD_PAYMENT_TYPE_SUCCESS = "ADD_PAYMENT_TYPE_SUCCESS";

export const DELETE_PAYMENT_TYPE_REQUEST = "DELETE_PAYMENT_TYPE_REQUEST";
export const DELETE_PAYMENT_TYPE_FAIL = "DELETE_PAYMENT_TYPE_FAIL";
export const DELETE_PAYMENT_TYPE_SUCCESS = "DELETE_PAYMENT_TYPE_SUCCESS";

export const GET_PAYMENT_TYPE_SUCCESS = "GET_PAYMENT_TYPE_SUCCESS";
export const GET_PAYMENT_TYPE_REQUEST = "GET_PAYMENT_TYPE_REQUEST";
export const GET_PAYMENT_TYPE_FAIL = "GET_PAYMENT_TYPE_FAIL";

export const UPDATE_PAYMENT_TYPE_REQUEST = "UPDATEPAYMENT_TYPE_REQUEST";
export const UPDATE_PAYMENT_TYPE_SUCCESS = "UPDATE_PAYMENT_TYPE_SUCCESS";
export const UPDATE_PAYMENT_TYPE_FAIL = "UPDATE_PAYMENT_TYPE_FAIL";

export const ADD_EXPENSES_REQUEST = "ADD_EXPENSES_REQUEST";
export const ADD_EXPENSES_FAIL = "ADD_EXPENSES_FAIL";
export const ADD_EXPENSES_SUCCESS = "ADD_EXPENSES_SUCCESS";

export const ADD_EXPENSES_CATEGORY_REQUEST = "ADD_EXPENSES_CATEGORY_REQUEST";
export const ADD_EXPENSES_CATEGORY_FAIL = "ADD_EXPENSES_CATEGORY_FAIL";
export const ADD_EXPENSES_CATEGORY_SUCCESS = "ADD_EXPENSES_CATEGORY_SUCCESS";

export const DELETE_EXPENSES_REQUEST = "DELETE_EXPENSES_REQUEST";
export const DELETE_EXPENSES_FAIL = "DELETE_EXPENSES_FAIL";
export const DELETE_EXPENSES_SUCCESS = "DELETE_EXPENSES_SUCCESS";

export const GET_EXPENSES_SUCCESS = "GET_EXPENSES_SUCCESS";
export const GET_EXPENSES_REQUEST = "GET_EXPENSES_REQUEST";
export const GET_EXPENSES_FAIL = "GET_EXPENSES_FAIL";

export const GET_EXPENSES_CARTEGORY_SUCCESS = "GET_EXPENSES_CARTEGORY_SUCCESS";
export const GET_EXPENSES_CARTEGORY_REQUEST = "GET_EXPENSES_CARTEGORY_REQUEST";
export const GET_EXPENSES_CARTEGORY_FAIL = "GET_EXPENSES_CARTEGORY_FAIL";

export const UPDATE_EXPENSES_REQUEST = "UPDATEEXPENSES_REQUEST";
export const UPDATE_EXPENSES_SUCCESS = "UPDATE_EXPENSES_SUCCESS";
export const UPDATE_EXPENSES_FAIL = "UPDATE_EXPENSES_FAIL";

export const ADD_DEPOSIT_REQUEST = "ADD_DEPOSIT_REQUEST";
export const ADD_DEPOSIT_SUCCESS = "ADD_DEPOSIT_SUCCESS";
export const ADD_DEPOSIT_FAIL = "ADD_DEPOSIT_FAIL";

export const GET_TOTAL_DEPOSIT_REQUEST = "GET_TOTAL_DEPOSIT_REQUEST";
export const GET_TOTAL_DEPOSIT_SUCCESS = "GET_TOTAL_DEPOSIT_SUCCESS";
export const GET_TOTAL_DEPOSIT_FAIL = "GET_TOTAL_DEPOSIT_FAIL";

export const UPDATE_DEPOSIT_REQUEST = "UPDATE_DEPOSIT_REQUEST";
export const UPDATE_DEPOSIT_SUCCESS = "UPDATE_DEPOSIT_SUCCESS";
export const UPDATE_DEPOSIT_FAIL = "UPDATE_DEPOSIT_FAIL";

// Reportings

export const GET_OUT_OF_STOCK_REQUEST = "GET_OUT_OF_STOCK_REQUEST";
export const GET_OUT_OF_STOCK_SUCCESS = "GET_OUT_OF_STOCK_SUCCESS";
export const GET_OUT_OF_STOCK_FAIL = "GET_OUT_OF_STOCK_FAIL";

export const GET_PRODUCT_PRICE_REQUEST = "GET_PRODUCT_PRICE_REQUEST";
export const GET_PRODUCT_PRICE_SUCCESS = "GET_PRODUCT_PRICE_SUCCESS";
export const GET_PRODUCT_PRICE_FAIL = "GET_PRODUCT_PRICE_FAIL";

export const GET_SALES_REPORT_REQUEST = "GET_SALES_REPORT_REQUEST";
export const GET_SALES_REPORT_SUCCESS = "GET_SALES_REPORT_SUCCESS";
export const GET_SALES_REPORT_FAIL = "GET_SALES_REPORT_FAIL";

export const GET_DEPOSIT_REPORT_REQUEST = "GET_DEPOSIT_REPORT_REQUEST";
export const GET_DEPOSIT_REPORT_SUCCESS = "GET_DEPOSIT_REPORT_SUCCESS";
export const GET_DEPOSIT_REPORT_FAIL = "GET_DEPOSIT_REPORT_FAIL";

export const GET_STOCK_LEVEL_REPORT_REQUEST = "GET_STOCK_LEVEL_REPORT_REQUEST";
export const GET_STOCK_LEVEL_REPORT_SUCCESS = "GET_STOCK_LEVEL_REPORT_SUCCESS";
export const GET_STOCK_LEVEL_REPORT_FAIL = "GET_STOCK_LEVEL_REPORT_FAIL";

export const GET_PROFIT_OR_LOSS_LEVEL_REPORT_REQUEST = "GET_PROFIT_OR_LOSS_LEVEL_REPORT_REQUEST";
export const GET_PROFIT_OR_LOSS_LEVEL_REPORT_SUCCESS = "GET_PROFIT_OR_LOSS_LEVEL_REPORT_SUCCESS";
export const GET_PROFIT_OR_LOSS_LEVEL_REPORT_FAIL = "GET_PROFIT_OR_LOSS_LEVEL_REPORT_FAIL";


export const GET_ALL_CUSTOMERS_REQUEST = "GET_ALL_CUSTOMERS_REQUEST"
export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS"
export const GET_ALL_CUSTOMERS_FAIL = "GET_ALL_CUSTOMERS_FAIL"

export const REGISTER_CUSTOMERS_REQUEST = "REGISTER_CUSTOMERS_REQUEST"
export const REGISTER_CUSTOMERS_SUCCESS = "REGISTER_CUSTOMERS_SUCCESS"
export const REGISTER_CUSTOMERS_FAIL = "REGISTER_CUSTOMERS_FAIL"

export const GET_CUSTOMERS_TRANSACTIONS_REQUEST = "GET_CUSTOMERS_TRANSACTIONS_REQUEST"
export const GET_CUSTOMERS_TRANSACTIONS_SUCCESS = "GET_CUSTOMERS_TRANSACTIONS_SUCCESS"
export const GET_CUSTOMERS_TRANSACTIONS_FAIL = "GET_CUSTOMERS_TRANSACTIONS_FAIL"

export const GET_CUSTOMERS_DEPOSITS_REQUEST = "GET_CUSTOMERS_DEPOSITS_REQUEST"
export const GET_CUSTOMERS_DEPOSITS_SUCCESS = "GET_CUSTOMERS_DEPOSITS_SUCCESS"
export const GET_CUSTOMERS_DEPOSITS_FAIL = "GET_CUSTOMERS_DEPOSITS_FAIL"

export const GET_CUSTOMERS_PURCHASED_REQUEST = "GET_CUSTOMERS_PURCHASED_REQUEST"
export const GET_CUSTOMERS_PURCHASED_SUCCESS = "GET_CUSTOMERS_PURCHASED_SUCCESS"
export const GET_CUSTOMERS_PURCHASED_FAIL = "GET_CUSTOMERS_PURCHASED_FAIL"

export const UPDATE_CUSTOMERS_REQUEST = "UPDATE_CUSTOMERS_REQUEST"
export const UPDATE_CUSTOMERS_SUCCESS = "UPDATE_CUSTOMERS_SUCCESS"
export const UPDATE_CUSTOMERS_FAIL = "UPDATE_CUSTOMERS_FAIL"

