export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT = "LOGOUT";

export const ADD_SUPPLIERS_REQUEST = "ADD_SUPPLIERS_REQUEST";
export const ADD_SUPPLIERS_FAIL = "ADD_SUPPLIERS_FAIL";
export const ADD_SUPPLIERS_SUCCESS = "ADD_SUPPLIERS_SUCCESS";

export const DELETE_SUPPLIERS_REQUEST = "DELETE_SUPPLIERS_REQUEST";
export const DELETE_SUPPLIERS_FAIL = "DELETE_SUPPLIERS_FAIL";
export const DELETE_SUPPLIERS_SUCCESS = "DELETE_SUPPLIERS_SUCCESS";

export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_REQUEST = "GET_SUPPLIERS_REQUEST";
export const GET_SUPPLIERS_FAIL = "GET_SUPPLIERS_FAIL";

export const UPDATE_SUPPLIER_REQUEST = "UPDATE_SUPPLIER_REQUEST";
export const UPDATE_SUPPLIERS_SUCCESS = "UPDATE_SUPPLIERS_SUCCESS";
export const UPDATE_SUPPLIERS_FAIL = "UPDATE_SUPPLIERS_FAIL";

export const ADD_BRAND_REQUEST = "ADD_BRAND_REQUEST";
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS";
export const ADD_BRAND_FAIL = "ADD_BRAND_FAIL";

export const GET_BRANDS_REQUEST = "GET_BRANDS_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAIL = "GET_BRAND_FAIL";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAIL = "DELETE_BRAND_FAIL";

export const UPDATE_BRANDS_REQUEST = "UPDATE_BRANDS_REQUEST";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_FAIL";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const GET_PRODUCT_BY_BARCODE_REQUEST = "GET_PRODUCT_BY_BARCODE_REQUEST";
export const GET_PRODUCT_BY_BARCODE_SUCCESS = "GET_PRODUCT_BY_BARCODE_SUCCESS";
export const GET_PRODUCT_BY_BARCODE_FAIL = "GET_PRODUCT_BY_BARCODE_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const ADD_SALES_REQUEST = "ADD_SALES_REQUEST";
export const ADD_SALES_SUCCESS = "ADD_SALES_SUCCESS";
export const ADD_SALES_FAIL = "ADD_SALES_FAIL";

export const ADD_SALES_DATA_REQUEST = "ADD_SALES_DATA_REQUEST";
export const ADD_SALES_DATASUCCESS = "ADD_SALES_DATA_SUCCESS";
export const ADD_SALES_DATA_FAIL = "ADD_SALES_DATA_FAIL";

export const ADD_STAFF_REQUEST = "ADD_STAFF_REQUEST";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAIL = "ADD_STAFF_FAIL";

export const GET_STAFF_REQUEST = "GET_STAFF_REQUEST";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const GET_STAFF_FAIL = "GET_STAFF_FAIL";

export const GET_STORE_REQUEST = "GET_STORE_REQUEST";
export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const GET_STORE_FAIL = "GET_STORE_FAIL";

export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST";
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS";
export const ADD_STORE_FAIL = "ADD_STORE_FAIL";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_PURCHASE_REQUEST = "GET_PURCHASE_REQUEST";
export const GET_PURCHASE_SUCCESS = "GET_PURCHASE_SUCCESS";
export const GET_PURCHASE_FAIL = "GET_PURCHASE_FAIL";

export const ADD_PURCHASE_REQUEST = "ADD_PURCHASE_REQUEST";
export const ADD_PURCHASE_SUCCESS = "ADD_PURCHASE_SUCCESS";
export const ADD_PURCHASE_FAIL = "ADD_PURCHASE_FAIL";
