export const COMPANY_NAME = "Solace Medicare hospital."
export const COMPANY_EMAIL = "Solacehospital22@gmail.com"
export const COMPANY_ADDRESS = "Modakeke, Osun State."
export const COMPANY_PHONE = "08035992252"
export const COMPANY_INITIALS = "SOC"
